# Generated by Django 4.1.5 on 2023-05-18 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='email',
            name='nome',
            field=models.CharField(default='Nome', max_length=100),
        ),
        migrations.AddField(
            model_name='email',
            name='sobrenome',
            field=models.CharField(default='Sobrenome', max_length=100),
        ),
    ]
